development:
  clients:
    default:
      database: birds
      hosts:
        - 127.0.0.1:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
  # Configure Mongoid specific options. (optional)
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: bird_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1